apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t0xf36jzw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t0xf36jzw-nodejs 
  name: t0xf36jzw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: t0xf36jzw-nodejs 
